### PR TITLE
fix: search on mobile and make url relative

### LINKED ISSUE #171: Search field doesn't work on mobile
See https://github.com/reuixiy/hugo-theme-meme/pull/165#issuecomment-632168950

### PR DESCRIPTION
**Pull request by reuixiy**
Fixes #171

### CODE REVIEW

File: assets/js/nav-toggle.js [hunk 1]
```diff
@@ -62,6 +62,12 @@ window.addEventListener(
 window.addEventListener(
     'resize',
     throttle(function() {
+        // https://github.com/reuixiy/hugo-theme-meme/issues/171
+        const input = document.getElementById('search-input');
+        if (input && input === document.activeElement) {
+            return;
+        }
+
         closeNav();
```
Comment (palant) [inline assets/js/nav-toggle.js:71]: Why are we doing this in the first place? I guess the idea is to get rid of artifacts when the user makes the window bigger and the nav toggle is no longer visible? Then maybe we should check `document.querySelector(".nav-toggle").offsetWidth` and call `closeNav()` if it's zero, completely independent of the search fields.

File: assets/js/lunr-search.js [hunk 2]
```diff
@@ -59,13 +59,21 @@
 
     function searchDone() {
         form.removeAttribute("data-running");
+
+        // A magic trick to make search field loses focus on mobile,
+        // which prevents the virtual keyboard from popping up.
+        const header = document.querySelector('.header');
+        if (header && header.className !== 'header') {
```
Comment (palant) [inline assets/js/lunr-search.js:66]: `header && header.classList.contains("open")` I guess? This shouldn't be triggered by random classes that the site added to the header.

File: assets/js/nav-toggle.js (hunk 1 above)
Comment (reuixiy) [reply assets/js/nav-toggle.js:71]: > Why are we doing this in the first place? I guess the idea is to get rid of artifacts when the user makes the window bigger and the nav toggle is no longer visible?

The `resize` listener? Yes.

> Then maybe we should check `document.querySelector(".nav-toggle").offsetWidth` and call `closeNav()` if it's zero, completely independent of the search fields.

Nope, we check this inside of the `closeNav()` function, see [here](https://github.com/reuixiy/hugo-theme-meme/blob/4c6097a906dac7c4109445b4f2d63574b53b155a/assets/js/nav-toggle.js#L70).

This `if`, however, prevents the drop-down menu from being collapsed by a `resize` event produced by the popped keyboard when search field is focused - although I don't know why it exists.

File: assets/js/lunr-search.js (hunk 2 above)
Comment (reuixiy) [reply assets/js/lunr-search.js]: I don't know why, but `header.classList.contains("hide")` works when I tested with a real device, kinda weird...

File: assets/js/nav-toggle.js (hunk 1 above)
Comment (palant) [reply assets/js/nav-toggle.js]: > Nope, we check this inside of the `closeNav()` function, see [here](https://github.com/reuixiy/hugo-theme-meme/blob/4c6097a906dac7c4109445b4f2d63574b53b155a/assets/js/nav-toggle.js#L70).

I didn't mean checking whether the menu is open - I meant checking whether the nav toggle is still visible in general. The `.nav-toggle` element is only visible when the window size is small, we can check that and close the menu only if it isn't visible any more (window size got large enough to display the menu permanently).

Comment (reuixiy) [reply assets/js/nav-toggle.js]: I got little puzzled... Could you create a new commit for this?

Comment (palant) [reply assets/js/nav-toggle.js]: Done, does it make sense now? Note that I had to remove the fade logic - there is no fading animation in this scenario, so the nav curtain remains visible.

Comment (palant) [reply assets/js/nav-toggle.js]: Reproduced the issue with nav curtain remaining visible when resizing a small browser window on palant.info in both Firefox and Chrome.

Comment (palant) [reply assets/js/nav-toggle.js]: Alternatively, it should be possible to listen to the `(max-width: $maxWidth)` media query instead of window resizes. One complication that probably makes it not worth doing: with this variable being calculated in SASS, it would have to be exposed somewhere - e.g. as a CSS variable on the document root.

Comment (reuixiy) [reply assets/js/nav-toggle.js]: Nice! Works like a charm! I'll try the media query approach.
