### PR TITLE
fix: When scrolling to an anchor, account for the header height (fixes #146)

### LINKED ISSUE #146: Fixed position header messes up internal linking
A link to a blog entry might go to a specific heading, e.g. when clicking a ToC table entry. With MemE this will currently result in the heading being hidden below the header rather than visible below it. It's a common issue and I only found [this solution](https://stackoverflow.com/a/28824157/785541) and variations of it. The issue here: it only works if header size is a known fixed value.

So it seems that the possible solutions are:

* Make the header non-fixed - it will become invisible when you scroll down.
* Implement some dynamic switching between fixed/non-fixed as seen on some websites - personally, I consider that behavior highly annoying.
* Calculate the header height based on the height of the largest element, for me it will be calc(2em + 38px) - that's making lots of assumptions, in particular that the header elements don't wrap.
* Set a CSS variable dynamically, similar to how width of `.main-inner` is currently being measured.

I've added the following custom CSS now:

```
[id]::before
{
  content: "";
  display: block;
  visibility: hidden;
  height: calc(38px + 2em);
  margin: calc(-38px - 2em) 0 0;
}
```

This seems to work pretty well. I can only see an issue if I switch to text-only zoom in Firefox and make the text big enough for the header to wrap onto two lines - and even then the heading is still readable. But measuring header height dynamically in addition might still be a good idea.

### PR DESCRIPTION
**Pull request by palant**
This implements the work-around described in #146. Since the header height has to be known, this will do an approximate calculation of the header height in CSS (already works well enough for me under most circumstances). The header will then be measured precisely by JavaScript if enabled.

### CODE REVIEW

File: assets/js/header.js [hunk 1]
```diff
@@ -18,6 +18,16 @@ if (mainInner !== null) {
 headerInner.style.setProperty('opacity', 1);
 
 
+// Measure header height for the scrolling fix
+{
```
Comment (palant) [inline assets/js/header.js:22]: The block here is necessary to avoid declaring constants at the top level of the script - this will conflict with another declaration of `const header` elsewhere. It might generally be a good idea to wrap each script file in a block to give it its own scope - this will make sure there are no conflicts between declarations in different script files.

File: assets/scss/layout/_header.scss [hunk 2]
```diff
@@ -48,4 +50,33 @@
...
+            max(
+                /* menu */
+                #{$fontSize * /* .nav font size */ 0.8 * /* .menu line height */ 1.5},
+                /* brand */
+                #{$brandHeight}
+            ) + #{/* .header-wrapper top+bottom margin */ 2 * $fontSize}
+        );
+
+        /* Work-around for anchors being hidden below the header */
+        p, div, ul, form, main, footer, nav, section, h1, h2, h3, h4, h5, h6
```
Comment (reuixiy) [inline assets/scss/layout/_header.scss:70]: Wait, I don't think we need to select so many elements - this may cause some bugs, such as the one I found on your site:



So maybe just headings?

**Comment by palant** [comment]
It isn't just headings - there is scrolling to footnotes and other elements as well. I shortened the list but I'm not quite happy with lists not being on there. Maybe a better solution would be limiting this to `#main`.

**Comment by reuixiy** [comment]
Agreed. It would be better to limit this to `#main`.

**Comment by palant** [comment]
There you go, done.

**Comment by palant** [comment]
Noticed that I had all the rules defined within `:root` - this isn't necessary, fixed.
